name: Build Kernel Module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential linux-headers-$(uname -r)

    - name: Compile module
      run: make

    - name: Load module
      run: sudo insmod hello_world.ko

    - name: Verify module load
      run: sudo dmesg | grep "Module started"

    - name: Unload module
      run: sudo rmmod hello_world

    - name: Verify module unload
      run: sudo dmesg | grep "Module exited"
